export const RESERVATION_ERROR_NOT_FOUND = "Reservation not found!";

export const RESERVATION_STATUS = {
  PENDING: "PENDING",
  REJECTED: "REJECTED",
  APPROVED: "APPROVED",
  LEASED: "LEASED",
  CANCELLED: "CANCELLED",
};
