export const WORK_ORDER_ERROR_NOT_FOUND = "Work Order not found!";

export const WORK_ORDER_STATUS = {
  PENDING: "PENDING",
  INPROGRESS: "INPROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const WORK_ORDER_TYPE = {
  BURIAL: "BURIAL",
  MAINTENANCE: "MAINTENANCE"
};
